/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import accesoDatos.*;
import entidades.Asignatura;
import entidades.Estudiante;
import entidades.Matricula;
import entidades.PeriodoAcademico;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import javax.swing.*;
import javax.swing.table.*;
import logica.*;
/**
 *
 * @author Kenner
 */
public class Presentacion extends javax.swing.JFrame {

    static ArrayList<Estudiante> estudiantes; 
    static ArrayList<Asignatura> asignaturas;
    static ArrayList<Matricula> matriculas;
    static PeriodoAcademico periodo = new PeriodoAcademico(2020, "I");
    static GregorianCalendar c = new GregorianCalendar();

    /**
     * Creates new form Presentacion
     */
    public Presentacion() {
        initComponents();
        lblPeriodoInicio.setText(periodo.toString());
        estudiantes = DatoEstudiante.getContenido();
        asignaturas = DatoAsignatura.getContenido();
        matriculas = DatoMatricula.getContenido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        btnRAsignatura = new javax.swing.JButton();
        btnREstudiante = new javax.swing.JButton();
        btnMatricula = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnRNotas = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        lblPeriodoInicio = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCodigoA = new javax.swing.JTextField();
        txtNombreA = new javax.swing.JTextField();
        cboCiclo = new javax.swing.JComboBox();
        cboCreditos = new javax.swing.JComboBox();
        btnRegistrarA = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreE = new javax.swing.JTextField();
        txtApellidosE = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtCodigoE = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnRegistrarE = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtCodigoEM = new javax.swing.JTextField();
        BtnBuscarEstudiante = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtApellidosEM = new javax.swing.JTextField();
        txtNombreEM = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDireccionEM = new javax.swing.JTextField();
        cboAsignaturaM = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        txtDniEM = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursosM = new javax.swing.JTable();
        BtnAddCursoM = new javax.swing.JButton();
        btnRegistrarM = new javax.swing.JButton();
        cboCicloM = new javax.swing.JComboBox();
        lblCodigoM = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNotas = new javax.swing.JTable();
        btnSiguiente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCodigoMNotas = new javax.swing.JTextField();
        txtCodigoENotas = new javax.swing.JTextField();
        txtApellidosNotas = new javax.swing.JTextField();
        txtNombreENotas = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        lblMatriculasRestantes = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtCodEDatoE = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDatosE = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        txtDniEDatosE = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtApellidosEDatosE = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtNombreEDatosE = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtDireccionEDatosE = new javax.swing.JTextField();
        btnRegresarDatosE = new javax.swing.JButton();
        btnBuscarDatosE = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtCodADatosA = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtNombreADatosA = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtCicloADatosA = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtNCreditosADatosA = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDatosA = new javax.swing.JTable();
        btnRegresarDatosA = new javax.swing.JButton();
        btnBuscarDatosA = new javax.swing.JButton();
        txtPeriodoAcademicoDatosA = new javax.swing.JTextField();

        jScrollPane3.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRAsignatura.setText("Asignatura");
        btnRAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAsignaturaActionPerformed(evt);
            }
        });

        btnREstudiante.setText("Estudiante");
        btnREstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREstudianteActionPerformed(evt);
            }
        });

        btnMatricula.setText("Matricula");
        btnMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatriculaActionPerformed(evt);
            }
        });

        jLabel17.setText("Registrar");

        btnRNotas.setText("Notas");
        btnRNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRNotasActionPerformed(evt);
            }
        });

        jLabel22.setText("Periodo Academico: ");

        lblPeriodoInicio.setText("periodo");

        jLabel23.setText("Listados");

        jButton1.setText("Datos Estudiante");

        jButton2.setText("Datos Asignatura");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPeriodoInicio)
                .addGap(208, 208, 208))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel17)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(btnRAsignatura)
                                .addGap(18, 18, 18)
                                .addComponent(btnREstudiante)
                                .addGap(18, 18, 18)
                                .addComponent(btnMatricula)
                                .addGap(18, 18, 18)
                                .addComponent(btnRNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton1)
                        .addGap(33, 33, 33)
                        .addComponent(jButton2)))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lblPeriodoInicio))
                .addGap(33, 33, 33)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRAsignatura)
                    .addComponent(btnREstudiante)
                    .addComponent(btnMatricula)
                    .addComponent(btnRNotas))
                .addGap(40, 40, 40)
                .addComponent(jLabel23)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inicio", jPanel4);

        jLabel6.setText("Codigo");

        jLabel7.setText("Nombre");

        jLabel8.setText("Ciclo");

        jLabel9.setText("N°Creditos");

        cboCiclo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "II", "III", "IV", "V", "VI", "VII", "VII", "IX", "X" }));

        cboCreditos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        btnRegistrarA.setText("Registrar");
        btnRegistrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboCreditos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboCiclo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreA, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtCodigoA))
                .addGap(73, 73, 73)
                .addComponent(btnRegistrarA)
                .addGap(219, 219, 219))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCodigoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnRegistrarA)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cboCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(cboCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(285, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar Asignatura", jPanel2);

        jLabel1.setText("Nombres");

        jLabel2.setText("Apellidos");

        jLabel3.setText("DNI");

        jLabel4.setText("Codigo");

        jLabel5.setText("Direccion");

        btnRegistrarE.setText("Registrar");
        btnRegistrarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnRegistrarE))
                    .addComponent(txtApellidosE, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoE, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidosE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro Estudiante", jPanel1);

        jLabel11.setText("Codigo Estudiante");

        BtnBuscarEstudiante.setText("Aceptar");
        BtnBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarEstudianteActionPerformed(evt);
            }
        });

        jButton5.setText("Cancelar");

        jLabel12.setText("Nombres");

        jLabel13.setText("Apellidos");

        jLabel14.setText("DNI");

        txtApellidosEM.setEnabled(false);

        txtNombreEM.setEnabled(false);

        jLabel15.setText("Direccion");

        txtDireccionEM.setEnabled(false);

        cboAsignaturaM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Asignaturas" }));

        jLabel16.setText("Asignatura a Matricular");

        txtDniEM.setEnabled(false);

        tblCursosM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Ciclo", "Creditos"
            }
        ));
        jScrollPane1.setViewportView(tblCursosM);
        if (tblCursosM.getColumnModel().getColumnCount() > 0) {
            tblCursosM.getColumnModel().getColumn(0).setMaxWidth(78);
            tblCursosM.getColumnModel().getColumn(2).setMaxWidth(60);
            tblCursosM.getColumnModel().getColumn(3).setMaxWidth(60);
        }

        BtnAddCursoM.setText("Añadir");
        BtnAddCursoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddCursoMActionPerformed(evt);
            }
        });

        btnRegistrarM.setText("Registrar Matricula");
        btnRegistrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMActionPerformed(evt);
            }
        });

        cboCicloM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1er Ciclo", "2do Ciclo", "3er Ciclo", "4to Ciclo", "5to Ciclo", "6to Ciclo", "7mo Ciclo", "8vo Ciclo", "9no Ciclo", "10mo Ciclo" }));
        cboCicloM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCicloMActionPerformed(evt);
            }
        });

        lblCodigoM.setText("############");
        lblCodigoM.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(20, 20, 20)
                                .addComponent(txtCodigoEM, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnBuscarEstudiante)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(50, 50, 50)
                                .addComponent(lblCodigoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDniEM, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreEM, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(15, 15, 15)
                                        .addComponent(txtDireccionEM, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtApellidosEM, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(cboCicloM, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboAsignaturaM, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAddCursoM, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarM)
                .addGap(139, 139, 139))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCodigoEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarEstudiante)
                    .addComponent(jButton5)
                    .addComponent(lblCodigoM, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtNombreEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtApellidosEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(txtDniEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAddCursoM)
                    .addComponent(jLabel16)
                    .addComponent(cboAsignaturaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCicloM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnRegistrarM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Matricula", jPanel3);

        tblNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Asignaturas Matriculadas", "Nota"
            }
        ));
        jScrollPane2.setViewportView(tblNotas);
        if (tblNotas.getColumnModel().getColumnCount() > 0) {
            tblNotas.getColumnModel().getColumn(1).setMaxWidth(60);
        }

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        jLabel10.setText("Codigo de Matricula");

        jLabel18.setText("Codigo de Estudiante");

        jLabel19.setText("Apellidos");

        jLabel20.setText("Nombre");

        txtCodigoMNotas.setEnabled(false);

        txtCodigoENotas.setEnabled(false);

        txtApellidosNotas.setEnabled(false);

        txtNombreENotas.setEnabled(false);

        jLabel21.setText("Matriculas restantes: ");

        lblMatriculasRestantes.setText("00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel10)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoMNotas)
                            .addComponent(txtCodigoENotas)
                            .addComponent(txtApellidosNotas, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txtNombreENotas)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel21)
                        .addGap(84, 84, 84)
                        .addComponent(lblMatriculasRestantes)
                        .addGap(127, 127, 127)
                        .addComponent(btnSiguiente)))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCodigoMNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCodigoENotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtApellidosNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreENotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguiente)
                    .addComponent(jLabel21)
                    .addComponent(lblMatriculasRestantes))
                .addGap(137, 137, 137))
        );

        jTabbedPane1.addTab("Calificaciones", jPanel6);

        jLabel24.setText("Codigo de Estudiante: ");

        tblDatosE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod. Matricula", "Periodo", "Asignatura", "Nota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblDatosE);
        if (tblDatosE.getColumnModel().getColumnCount() > 0) {
            tblDatosE.getColumnModel().getColumn(0).setMinWidth(88);
            tblDatosE.getColumnModel().getColumn(0).setPreferredWidth(88);
            tblDatosE.getColumnModel().getColumn(0).setMaxWidth(88);
            tblDatosE.getColumnModel().getColumn(1).setMinWidth(110);
            tblDatosE.getColumnModel().getColumn(1).setPreferredWidth(110);
            tblDatosE.getColumnModel().getColumn(1).setMaxWidth(110);
            tblDatosE.getColumnModel().getColumn(3).setMinWidth(65);
            tblDatosE.getColumnModel().getColumn(3).setPreferredWidth(65);
            tblDatosE.getColumnModel().getColumn(3).setMaxWidth(65);
        }

        jLabel25.setText("Dni: ");

        txtDniEDatosE.setEnabled(false);

        jLabel26.setText("Apellidos: ");

        txtApellidosEDatosE.setEnabled(false);

        jLabel27.setText("Nombre: ");

        txtNombreEDatosE.setEnabled(false);

        jLabel28.setText("Direccion: ");

        txtDireccionEDatosE.setEnabled(false);

        btnRegresarDatosE.setText("Regresar");
        btnRegresarDatosE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarDatosEActionPerformed(evt);
            }
        });

        btnBuscarDatosE.setText("Buscar");
        btnBuscarDatosE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDatosEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegresarDatosE, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(121, 121, 121)
                            .addComponent(jLabel24)
                            .addGap(18, 18, 18)
                            .addComponent(txtCodEDatoE, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(btnBuscarDatosE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtDniEDatosE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(59, 59, 59)
                                    .addComponent(jLabel26)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtApellidosEDatosE, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel28)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDireccionEDatosE, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17))))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addComponent(jLabel27)
                            .addGap(18, 18, 18)
                            .addComponent(txtNombreEDatosE, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtCodEDatoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDatosE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtDniEDatosE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtApellidosEDatosE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtNombreEDatosE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel28))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtDireccionEDatosE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresarDatosE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos Estudiante", jPanel5);

        jLabel29.setText("codigo de Asignatura:");

        jLabel30.setText("Periodo academico: ");

        jLabel31.setText("Nombre: ");

        txtNombreADatosA.setEnabled(false);

        jLabel32.setText("Ciclo: ");

        txtCicloADatosA.setEnabled(false);

        jLabel33.setText("N° Creditos");

        txtNCreditosADatosA.setEnabled(false);

        tblDatosA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cod. Estudiante", "Apellidos", "Nombre", "Direccion"
            }
        ));
        jScrollPane5.setViewportView(tblDatosA);

        btnRegresarDatosA.setText("Regresar");
        btnRegresarDatosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarDatosAActionPerformed(evt);
            }
        });

        btnBuscarDatosA.setText("Buscar");
        btnBuscarDatosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDatosAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegresarDatosA)
                .addGap(67, 67, 67))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel31)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(txtCicloADatosA, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNCreditosADatosA, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(txtNombreADatosA, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCodADatosA, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(txtPeriodoAcademicoDatosA, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarDatosA)
                .addGap(49, 49, 49))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(txtCodADatosA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDatosA)
                    .addComponent(txtPeriodoAcademicoDatosA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtNombreADatosA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtCicloADatosA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(txtNCreditosADatosA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnRegresarDatosA)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Datos Asignatura", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAActionPerformed
        String codigo = txtCodigoA.getText();
        String nombre = txtNombreA.getText();   
        if(ValidadorAsignatura.validarAsignatura(codigo, nombre)){
            resgistrarAsignatura(codigo,nombre);
        }
        txtCodigoA.setText("");
        txtNombreA.setText("");
        cboCiclo.setSelectedIndex(0);
        cboCreditos.setSelectedIndex(0);
    }//GEN-LAST:event_btnRegistrarAActionPerformed

    private void btnRegistrarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEActionPerformed
        String nombre = txtNombreE.getText();
        String apellidos= txtApellidosE.getText();
        String dni = txtDni.getText();
        String codigo = txtCodigoE.getText();
        String direccion  = txtDireccion.getText();
        if(ValidadorEstudiante.validarEstudiante(codigo,dni,apellidos,nombre,direccion)){
            registrarEstudiante(nombre,apellidos,dni,codigo,direccion);
        }
        txtNombreE.setText("");
        txtApellidosE.setText("");
        txtDni.setText("");
        txtCodigoE.setText("");
        txtDireccion.setText("");
    }//GEN-LAST:event_btnRegistrarEActionPerformed

    private void btnRAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAsignaturaActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnRAsignaturaActionPerformed

    private void btnREstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREstudianteActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnREstudianteActionPerformed

    private void btnMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatriculaActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btnMatriculaActionPerformed

    private void cboCicloMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCicloMActionPerformed
        // TODO add your handling code here:
        cboAsignaturaM.removeAllItems();
        for(Asignatura a : this.findCursos()){
            cboAsignaturaM.addItem(a.getNombre());
        }
    }//GEN-LAST:event_cboCicloMActionPerformed

    private void btnRegistrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMActionPerformed
        int nCursos = tblCursosM.getRowCount();
        String codigoE = txtCodigoEM.getText();
        registrarMatricula();
        jTabbedPane1.setSelectedIndex(0);
        resetModel(tblCursosM,new String[]{"Codigo","Nombre","Ciclo","Creditos"},
                new int[]{88,350,60,60},new boolean[]{false,false,false,false});
    }//GEN-LAST:event_btnRegistrarMActionPerformed

    private void BtnAddCursoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddCursoMActionPerformed
        Asignatura temp_A = this.findCursos().get(cboAsignaturaM.getSelectedIndex());
        ((DefaultTableModel)tblCursosM.getModel()).addRow(new Object[]{temp_A.getCodigo(),temp_A.getNombre(),temp_A.getCiclo(),temp_A.getNumeroCreditos()});
    }//GEN-LAST:event_BtnAddCursoMActionPerformed

    private void BtnBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarEstudianteActionPerformed
        String codigo = txtCodigoEM.getText();
        Estudiante temp_E = new Estudiante();
        temp_E.setCodigo(codigo);
        temp_E = estudiantes.get(estudiantes.indexOf(temp_E));
        txtNombreEM.setText(temp_E.getNombre());
        txtApellidosEM.setText(temp_E.getApellidos());
        txtDireccionEM.setText(temp_E.getDireccion());
        txtDniEM.setText(temp_E.getDni());
    }//GEN-LAST:event_BtnBuscarEstudianteActionPerformed

    private void btnRNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRNotasActionPerformed
        Matricula m = matriculasPorPeriodo(this.periodo).get(0);
        txtCodigoMNotas.setText(m.genCode());
        Estudiante e = m.getEstudiante();
        txtCodigoENotas.setText(e.getCodigo());
        txtApellidosNotas.setText(e.getApellidos());
        txtNombreENotas.setText(e.getNombre());
        generateTable(tblNotas,m);
        lblMatriculasRestantes.setText(Integer.toString(matriculasPorPeriodo(this.periodo).size()));
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btnRNotasActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        int restantes = Integer.parseInt(lblMatriculasRestantes.getText());
        int total = matriculasPorPeriodo(this.periodo).size();
        DefaultTableModel model = (DefaultTableModel) tblNotas.getModel();
        Matricula m = matriculasPorPeriodo(this.periodo).get(total-restantes);
        for(int i = 0; i<tblNotas.getRowCount();i++){
            System.out.println("Boton siguiente]"+m.getCursosMatriculados().get(i).getNombre());
            System.out.println("i:"+i);
            System.out.println(model.getValueAt(i,0));
            float nota = Float.parseFloat((String)model.getValueAt(i, 1));
            m.getCalificaciones().set(i, nota);
            DetalleMatriculas.modifyNota(m.genCode(), m.getCursosMatriculados().get(i).getCodigo(), nota);
        }
    
        lblMatriculasRestantes.setText(Integer.toString(Integer.parseInt(lblMatriculasRestantes.getText())-1));
        
        restantes = Integer.parseInt(lblMatriculasRestantes.getText())-1;
        if(restantes > 0){
            total = matriculasPorPeriodo(this.periodo).size();
            m = matriculasPorPeriodo(this.periodo).get(total-restantes);
            txtCodigoMNotas.setText(m.genCode());
            Estudiante e = m.getEstudiante();
            txtCodigoENotas.setText(e.getCodigo());
            txtApellidosNotas.setText(e.getApellidos());
            txtNombreENotas.setText(e.getNombre());
            generateTable(tblNotas,m);
            lblMatriculasRestantes.setText(Integer.toString(restantes));
            JOptionPane.showMessageDialog(null,"Registro exitoso");
            System.out.println("Registro exitoso");
        }else{
            JOptionPane.showMessageDialog(null,"Ya no quedan mas estudiantes por registrar");
            System.out.println("Se terminaron de registrar las notas");
            this.periodo = this.periodo.nextPeriodo();
            lblPeriodoInicio.setText(periodo.toString());
            jTabbedPane1.setSelectedIndex(0);
        }
        txtCodigoMNotas.setText("");
        txtCodigoENotas.setText("");
        txtApellidosNotas.setText("");
        txtNombreENotas.setText("");
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnBuscarDatosEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDatosEActionPerformed
        tblDatosE.removeAll();
        resetModel(tblDatosE,new String[]{"Cod. Matricula","Periodo","Asignatura","Nota"},
                new int[]{88,110,330,65},new boolean[]{false,false,false,false});
        String codE = txtCodEDatoE.getText();
        ArrayList<Asignatura> tempAsignaturas = new ArrayList<Asignatura>();
        Estudiante estudiante = new Estudiante();
        estudiante.setCodigo(codE);
        for(Estudiante e: estudiantes){
            if(e.equals(estudiante)){
                estudiante = e;
            }
        }
        txtDniEDatosE.setText(estudiante.getDni());
        txtApellidosEDatosE.setText(estudiante.getApellidos());
        txtNombreEDatosE.setText(estudiante.getNombre());
        txtDireccionEDatosE.setText(estudiante.getDireccion());
        for(Matricula m: matriculas){
            String codM = m.genCode();
            if(m.getEstudiante().equals(estudiante)){
                String tempPeriodo =m.getPeriodo().toString();
                for(int i = 0; i<m.getCursosMatriculados().size();i++){
                    Asignatura tempA = m.getCursosMatriculados().get(i);
                    if(!tempAsignaturas.contains(tempA)){
                        String nombreA = tempA.getNombre();
                        float nota = m.getCalificaciones().get(i);
                        tempAsignaturas.add(tempA);
                        ((DefaultTableModel)tblDatosE.getModel()).addRow(new Object[]{codM,tempPeriodo,nombreA,nota});
                    }
                }
            }
        }
    }//GEN-LAST:event_btnBuscarDatosEActionPerformed

    private void btnRegresarDatosEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarDatosEActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        txtCodEDatoE.setText("");
        txtDniEDatosE.setText("");
        txtApellidosEDatosE.setText("");
        txtNombreEDatosE.setText("");
        txtDireccionEDatosE.setText("");
    }//GEN-LAST:event_btnRegresarDatosEActionPerformed

    private void btnRegresarDatosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarDatosAActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        resetModel(tblDatosA,new String[]{"Cod. Estudiante","Apellidos","Nombre","Direccion"},
                new int[]{108,370,90,230},new boolean[]{false,false,false,false});
    }//GEN-LAST:event_btnRegresarDatosAActionPerformed

    private void btnBuscarDatosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDatosAActionPerformed
        ArrayList<Asignatura> tempAsignaturas = new ArrayList<Asignatura>();
        String codigoPA = txtPeriodoAcademicoDatosA.getText();
        String codigoA = txtCodADatosA.getText();
        tblDatosA.removeAll();
        for(int i = matriculas.size()-1;i>=0;i--){
            Matricula tempM = matriculas.get(i);
            if(tempM.getPeriodo().genCode().equals(codigoPA)){
                int indexCurso = tempM.tieneCurso(codigoPA);
                if(indexCurso!=-1){
                    Asignatura tempA = tempM.getCursosMatriculados().get(indexCurso);
                    Estudiante tempE = tempM.getEstudiante();
                    txtNombreADatosA.setText(tempA.getNombre());
                    txtCicloADatosA.setText(Integer.toString(tempA.getCiclo()));
                    txtNCreditosADatosA.setText(Integer.toString(tempA.getNumeroCreditos()));
                    String codE = tempE.getCodigo();
                    String apellidos = tempE.getApellidos();
                    String nombre = tempE.getNombre();
                    String direccion = tempE.getDireccion();
                    ((DefaultTableModel)tblDatosA.getModel()).addRow(new Object[]{codE,apellidos,nombre,direccion});
                }
            }
        }
    }//GEN-LAST:event_btnBuscarDatosAActionPerformed
    
    public void resgistrarAsignatura(String codigo, String nombreA) {
        int ciclo = cboCiclo.getSelectedIndex()+1;
        int numeroCreditos = cboCiclo.getSelectedIndex() + 1;
        Asignatura asignatura = new Asignatura(codigo, nombreA, ciclo, numeroCreditos);
        DatoAsignatura.escribirAsignatura(asignatura);
        asignaturas.add(asignatura);
    }
    
    public void registrarEstudiante(String nombre, String apellidos, String dni, String codigo, String direccion){
        Estudiante estudiante = new Estudiante(nombre,apellidos,dni,codigo,direccion);
        DatoEstudiante.escribirEstudiante(estudiante);
        estudiantes.add(estudiante);    
        System.out.println("Estudiante:["+codigo+"] registrado con exito");
        JOptionPane.showMessageDialog(null,"Estudiante:["+codigo+"] registrado con exito");
    }
    
       public void registrarMatricula(){
        Matricula m = new Matricula();
        m.setFecha(c);
        
        m.setPeriodo(periodo); 
        String codigo=lblCodigoM.getText();   
        String codigoE = txtCodigoEM.getText();
        Estudiante estudiante = estudiantes.get(estudiantes.indexOf(new Estudiante(codigoE,"","","","")));       
        m.setEstudiante(estudiante);
        DefaultTableModel model = (DefaultTableModel) tblCursosM.getModel();
        for(int i = 0; i<tblCursosM.getRowCount();i++){
            String codigoA = (String) model.getValueAt(i, 0);
            String nombre = (String) model.getValueAt(i, 1);
            int ciclo = (int) model.getValueAt(i, 2);
            int nCreditos = (int) model.getValueAt(i, 3);
            m.addAsignatura(new Asignatura(codigoA,nombre,ciclo,nCreditos));
            m.addCalificacion(0.0f);
            System.out.println(codigoA+" "+nombre+" "+ciclo+" "+nCreditos);
        }
        if(ValidadorMatricula.validarMatricula(codigoE, asignaturas)){
            matriculas.add(m);
            DatoMatricula.escribirMatricula(m);
            DetalleMatriculas.escribirMatricula(m);
        }
    }
    
    public void añadir(){
        ArrayList<Float> notas = new ArrayList<Float>();
        //añadir maximo 6 cursos 
        
        ArrayList[] items = {asignaturas, notas};
        
    }
    
    public ArrayList<Matricula> matriculasPorPeriodo(PeriodoAcademico pa){
        ArrayList<Matricula> data = new ArrayList<Matricula>();
        for(int i = matriculas.size()-1; i>=0 ; i--){
            System.out.println("buscando matricula en posicion: " + i);
            Matricula temp_m = matriculas.get(i);
            System.out.println(temp_m.toString());
            System.out.println("Periodo:" + temp_m.getPeriodo().toString());
            System.out.println("CodigoE:" + temp_m.getEstudiante().getCodigo());
            
            if(pa.genCode().equals(temp_m.genCode().substring(0,3))){
                data.add(temp_m);
            }
        }
        return data;
    }
    
    private ArrayList<Asignatura> findCursos(){
       int ciclo = cboCicloM.getSelectedIndex() + 1;
       ArrayList<Asignatura> cursoCiclo = new ArrayList<Asignatura>();
       for(Asignatura a: asignaturas){
           if(Integer.parseInt(a.getCodigo().substring(0,1))==ciclo){
               cursoCiclo.add(a);
           }
       }
       return cursoCiclo;
    }
    
    private void generateTable(JTable table, Matricula matricula) {
        DefaultTableModel model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return column!=0;
            }
        };
        model.addColumn("Asignaturas matricuados");
        model.addColumn("Nota");
        table.setModel(model);
        ArrayList<Asignatura> cursos = matricula.getCursosMatriculados();
        ArrayList<Float> notas = matricula.getCalificaciones();
        for(int i = 0; i< cursos.size(); i++){
            String[] data = {cursos.get(i).getNombre(),Float.toString(notas.get(i))};
            model.addRow(data);
        }
    }
    
    public void resetModel(JTable tabla, String[] columnas, int[] anchos, boolean[] editables){
        DefaultTableModel model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return editables[column];
            }
        };
        for(int i = 0;i<columnas.length;i++){
            model.addColumn(columnas[i]);
        }
        tabla.setModel(model);
        for(int i = 0;i<tabla.getColumnCount();i++){
            tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddCursoM;
    private javax.swing.JButton BtnBuscarEstudiante;
    private javax.swing.JButton btnBuscarDatosA;
    private javax.swing.JButton btnBuscarDatosE;
    private javax.swing.JButton btnMatricula;
    private javax.swing.JButton btnRAsignatura;
    private javax.swing.JButton btnREstudiante;
    private javax.swing.JButton btnRNotas;
    private javax.swing.JButton btnRegistrarA;
    private javax.swing.JButton btnRegistrarE;
    private javax.swing.JButton btnRegistrarM;
    private javax.swing.JButton btnRegresarDatosA;
    private javax.swing.JButton btnRegresarDatosE;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboAsignaturaM;
    private javax.swing.JComboBox cboCiclo;
    private javax.swing.JComboBox cboCicloM;
    private javax.swing.JComboBox cboCreditos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCodigoM;
    private javax.swing.JLabel lblMatriculasRestantes;
    private javax.swing.JLabel lblPeriodoInicio;
    private javax.swing.JTable tblCursosM;
    private javax.swing.JTable tblDatosA;
    private javax.swing.JTable tblDatosE;
    private javax.swing.JTable tblNotas;
    private javax.swing.JTextField txtApellidosE;
    private javax.swing.JTextField txtApellidosEDatosE;
    private javax.swing.JTextField txtApellidosEM;
    private javax.swing.JTextField txtApellidosNotas;
    private javax.swing.JTextField txtCicloADatosA;
    private javax.swing.JTextField txtCodADatosA;
    private javax.swing.JTextField txtCodEDatoE;
    private javax.swing.JTextField txtCodigoA;
    private javax.swing.JTextField txtCodigoE;
    private javax.swing.JTextField txtCodigoEM;
    private javax.swing.JTextField txtCodigoENotas;
    private javax.swing.JTextField txtCodigoMNotas;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionEDatosE;
    private javax.swing.JTextField txtDireccionEM;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDniEDatosE;
    private javax.swing.JTextField txtDniEM;
    private javax.swing.JTextField txtNCreditosADatosA;
    private javax.swing.JTextField txtNombreA;
    private javax.swing.JTextField txtNombreADatosA;
    private javax.swing.JTextField txtNombreE;
    private javax.swing.JTextField txtNombreEDatosE;
    private javax.swing.JTextField txtNombreEM;
    private javax.swing.JTextField txtNombreENotas;
    private javax.swing.JTextField txtPeriodoAcademicoDatosA;
    // End of variables declaration//GEN-END:variables
}
